name: Update Book Ranking

on:
  schedule:
    - cron: '*/5 * * * *'   # 매시간 10분마다 실행
  workflow_dispatch:         # 수동 실행도 허용

jobs:
  call-supabase:
    runs-on: ubuntu-22.04

    steps:
      - name: Check DNS resolution (for debugging)
        run: nslookup tbuoutcwvalrcdlajobk.supabase.co

      - name: Call Supabase Edge Function
        run: |
          curl --retry 3 --connect-timeout 10 -L -X POST \
            https://tbuoutcwvalrcdlajobk.supabase.co/functions/v1/user-book-ranking \
            -H "Authorization: Bearer $SUPABASE_SERVICE_ROLE_KEY"
        env:
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
